In [ ]:
import numpy as np

### Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0]))

In [10]:
q = int(input('Введите контрольное число для создания массива: '))
np.arange(q)

Введите контрольное число для создания массива array: 8


array([0, 1, 2, 3, 4, 5, 6, 7])

### Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [22]:
q = int(input('Введите число строк(=столбцов) для создания диагональной матрицы: '))
a = np.mat(np.random.randint(q, size = (q,q)))
print(a)
sum(np.diag(a))


Введите число строк(=столбцов) для создания диагональной матрицы: 8
[[1 6 1 1 6 6 1 3]
 [0 6 1 4 0 3 3 5]
 [5 6 3 7 2 7 7 5]
 [7 0 2 7 7 7 3 1]
 [2 7 5 4 7 0 1 1]
 [1 3 1 2 0 6 3 2]
 [1 2 7 2 1 6 6 5]
 [1 1 4 1 7 6 7 5]]


41

### Задание 3
Решите систему уравнений:
    4x + 2y + z = 4   
    x + 3y = 12   
    5y + 4z = -3   

In [34]:
b = np.array([[4,2,1], [1,3,0], [0,5,4]])
c = np.array([4,12,-3])

from numpy import linalg
print(linalg.solve(b,c))

[ 0.46666667  3.84444444 -5.55555556]


### Задача 4 домашнего задания  
Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем. Матрица в виде numpy array. На сайт заходит очередной посетитель, о покупках которого известно следующее: в переменной next_user_stats. Найдите самого похожего пользователя. Т.е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [61]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)
next_user_stats = np.array([0, 1, 2, 0, 0, 0])
next_user_stats_length = np.linalg.norm(next_user_stats)
match_matrix = {}
for user, val in enumerate(users_stats, start=1):
    user_length = np.linalg.norm(val)
    match_matrix[user] = np.dot(val, next_user_stats)/(next_user_stats_length*user_length)
#print(match_matrix)
print(f'Самый похожий пользователь - № {max(match_matrix, key = match_matrix.get)}')


Самый похожий пользователь - № 8
